import fs from 'fs';
import path from 'path';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const logic = fs.readFileSync(path.join(root, 'scripts/_hookLogic.txt'), 'utf8');

const formHook = `'use client';

import { useState, useEffect } from 'react';
import axios from 'axios';
import dayjs from 'dayjs';
import {
  API_BASE_URL,
  defaultProcessingTypes,
  producers,
} from '../constants';
import { formatDateTimeLocal } from '../utils/formatDateTimeLocal';
import { generateOrderSheet as generateOrderSheetPdf } from '../utils/exportOrderSheet';

export function useFermentationForm(session, shared) {
${logic}
  return {
    batchNumber, setBatchNumber,
    referenceNumber, setReferenceNumber,
    version, setVersion,
    fullReferenceNumber,
    experimentNumber, setExperimentNumber,
    processingType, setProcessingType,
    description, setDescription,
    farmerName, setFarmerName,
    type, setType,
    variety, setVariety,
    harvestDate, setHarvestDate,
    harvestAt, setHarvestAt,
    receivedAt, setReceivedAt,
    receivedWeight, setReceivedWeight,
    rejectWeight, setRejectWeight,
    defectWeight, setDefectWeight,
    damagedWeight, setDamagedWeight,
    lostWeight, setLostWeight,
    preprocessingWeight, setPreprocessingWeight,
    quality, setQuality,
    brix, setBrix,
    preStorage, setPreStorage,
    preStorageCondition, setPreStorageCondition,
    preFermentationStorageGoal, setPreFermentationStorageGoal,
    preFermentationStorageStart, setPreFermentationStorageStart,
    preFermentationStorageEnd, setPreFermentationStorageEnd,
    prePulped, setPrePulped,
    prePulpedDelva, setPrePulpedDelva,
    preFermentationTimeAfterPulping, setPreFermentationTimeAfterPulping,
    prePulpedWeight, setPrePulpedWeight,
    cherryType, setCherryType,
    fermentationCherryWeight, setFermentationCherryWeight,
    fermentation, setFermentation,
    tank, setTank,
    fermentationStarter, setFermentationStarter,
    fermentationStarterAmount, setFermentationStarterAmount,
    gas, setGas,
    pressure, setPressure,
    isSubmerged, setIsSubmerged,
    totalVolume, setTotalVolume,
    waterUsed, setWaterUsed,
    starterUsed, setStarterUsed,
    stirring, setStirring,
    fermentationTemperature, setFermentationTemperature,
    pH, setPH,
    fermentationTimeTarget, setFermentationTimeTarget,
    fermentationStart, setFermentationStart,
    fermentationEnd, setFermentationEnd,
    finalPH, setFinalPH,
    finalTDS, setFinalTDS,
    finalTemperature, setFinalTemperature,
    postFermentationWeight, setPostFermentationWeight,
    postPulped, setPostPulped,
    postPulpedDelva, setPostPulpedDelva,
    secondFermentation, setSecondFermentation,
    secondFermentationTank, setSecondFermentationTank,
    secondPostPulped, setSecondPostPulped,
    secondPostPulpedDelva, setSecondPostPulpedDelva,
    secondWashed, setSecondWashed,
    secondFermentationCherryWeight, setSecondFermentationCherryWeight,
    secondFermentationPulpedWeight, setSecondFermentationPulpedWeight,
    secondStarterType, setSecondStarterType,
    secondGas, setSecondGas,
    secondPressure, setSecondPressure,
    secondIsSubmerged, setSecondIsSubmerged,
    secondTotalVolume, setSecondTotalVolume,
    secondWaterUsed, setSecondWaterUsed,
    secondMosstoUsed, setSecondMosstoUsed,
    secondActualVolume, setSecondActualVolume,
    secondTemperature, setSecondTemperature,
    secondFermentationTimeTarget, setSecondFermentationTimeTarget,
    secondFermentationStart, setSecondFermentationStart,
    secondFermentationEnd, setSecondFermentationEnd,
    dryingArea, setDryingArea,
    avgTemperature, setAvgTemperature,
    preDryingWeight, setPreDryingWeight,
    finalMoisture, setFinalMoisture,
    postDryingWeight, setPostDryingWeight,
    dryingStart, setDryingStart,
    dryingEnd, setDryingEnd,
    secondDrying, setSecondDrying,
    secondDryingArea, setSecondDryingArea,
    secondAverageTemperature, setSecondAverageTemperature,
    secondFinalMoisture, setSecondFinalMoisture,
    secondPostDryingWeight, setSecondPostDryingWeight,
    secondDryingStart, setSecondDryingStart,
    secondDryingEnd, setSecondDryingEnd,
    rehydration, setRehydration,
    storage, setStorage,
    storageTemperature, setStorageTemperature,
    hullingTime, setHullingTime,
    bagType, setBagType,
    postHullingWeight, setPostHullingWeight,
    productLine, setProductLine,
    wesorter, setWesorter,
    preClassifier, setPreClassifier,
    airlock, setAirlock,
    tankAmount, setTankAmount,
    leachateTarget, setLeachateTarget,
    leachate, setLeachate,
    brewTankTemperature, setBrewTankTemperature,
    waterTemperature, setWaterTemperature,
    coolerTemperature, setCoolerTemperature,
    drying, setDrying,
    availableBatches,
    availableTanks,
    isLoadingTanks,
    tankError,
    referenceMappings,
    availableProcessingTypes,
    fieldDisabled,
    detailsFieldDisabled,
    isSecondFermentationDisabled,
    isDetailsSecondFermentationDisabled,
    derivedDate,
    formatDateTimeLocal,
    handleBatchNumberChange,
    handleReferenceNumberChange,
    handleProcessingTypeChange,
    handleTankChange,
    handleSubmit,
    resetForm,
    checkExperimentNumber,
    generateOrderSheet,
    detailsData,
    setDetailsData,
    handleUpdateDetails,
    selectedBatch,
    setSelectedBatch,
    openDetailsDialog,
    setOpenDetailsDialog,
    handleDetailsClick,
    fetchDetailsData,
    fetchAvailableBatches,
    fetchAvailableTanks,
    fetchReferenceMappings,
    producers,
  };
}
`;

// Trim logic to form-relevant only - remove order book specific parts
let body = logic;

// Remove blocks that belong to order book
const removePatterns = [
  /  const \[fermentationData[\s\S]*?  const \[referenceMappings/,
];
// Actually simpler: keep full logic in one hook file useFermentationStation and split return only

fs.writeFileSync(path.join(root, 'hooks/useFermentationForm.js'), formHook);
console.log('wrote useFermentationForm.js', formHook.split('\n').length);
